### ISSUE TITLE
大佬，出错了。求解，谢谢。

### ISSUE THREAD

**Issue by qqvsmsn** [Myxpx/Send#3]
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.22.0) 
6Traceback (most recent call last): 
7 File "telecom.py", line 126, in <module> 
8 main_handler(1, 1) 
9 File "telecom.py", line 121, in main_handler 
10 content = format_msg() 
11 File "telecom.py", line 115, in format_msg 
12 str += item + "\r\n" 
13TypeError: unsupported operand type(s) for +: 'dict' and 'str' 
14Error: Process completed with exit code 1.

这个是用GITHUB ACTION跑的结果，不知道问题是哪里，请教，谢谢啊。

**Comment by qqvsmsn** [comment]
只是修改了手机号和pushplus的号码，然后运行出错。

**Comment by Myxpx** [comment]
看改过的，你那个有点问题，不能兑换话费，重新拉库，把手机号填上去就行了啦

**Comment by qqvsmsn** [comment]
非常感谢您，回复这么快，再次感谢，我去试试去。

**Comment by qqvsmsn** [comment]
我把原先的库删除了 ，重新fork的，然后更新电话号码，和pushplus，运行，没有出错，但是也没有收到pushplus的推送信息。
难道是我用的mail.yml有问题么，您能受累帮忙看看么。谢谢。要求可能有点儿多了，(⊙o⊙)…

**Comment by qqvsmsn** [comment]
另外，我把脚本放在QL上面，直接运行，中间没有任何提示，只有一个开始时间和结束时间，大约不到1分钟，(⊙o⊙)…

**Comment by Myxpx** [comment]
嗯，我是挂青龙的，不出错就没提示的，不用管他，签到这玩意没必要放心上随缘就好
